"""Generated pose library — {cat: {id: text}}. Regenerate via scratchpad/gen_poses.py."""

POSE_GROUPS = {
  "Portrait": {
    "square-shoulders-direct": "Shoulders squared to the camera, head level, gazing straight toward the lens with a relaxed neutral posture.",
    "slight-shoulder-turn-left": "Shoulders turned slightly to her left while her head rotates back to face the camera.",
    "three-quarter-right": "Body angled three-quarters to the right, head turned to look over toward the camera.",
    "chin-lowered-glance": "Chin dipped slightly downward with eyes lifted to meet the camera in a soft upward glance.",
    "chin-raised-up": "Chin lifted a little, head tilted back gently, gaze directed just above the lens.",
    "head-tilt-right": "Head tilted to the right shoulder, eyes looking toward the camera calmly.",
    "head-tilt-left": "Head tilted gently to the left, gaze soft and directed at the lens.",
    "over-shoulder-look": "Shoulders angled away with head turned back over one shoulder toward the camera.",
    "profile-left": "Full left profile, head facing sideways with gaze into the distance.",
    "profile-right": "Full right profile, chin level, eyes looking straight ahead off camera.",
    "hand-to-chin": "One hand lifted lightly to the chin, head tilted slightly, looking toward the camera.",
    "hand-on-collarbone": "One hand resting softly on her collarbone, shoulders relaxed, gaze at the lens.",
    "arms-crossed-relaxed": "Arms crossed loosely at the chest, shoulders open, head level and facing forward.",
    "fingers-through-hair": "One hand raised to run fingers through her hair, head tilted, eyes toward the camera.",
    "hand-behind-neck": "One hand lifted to the back of her neck, head turned slightly, gazing at the lens.",
    "looking-away-right": "Head turned to look off to the right, shoulders facing forward, expression thoughtful.",
    "looking-away-left": "Gaze directed off to the left, head slightly turned, shoulders squared.",
    "downcast-eyes": "Head level with eyes cast gently downward, shoulders relaxed and still.",
    "upward-gaze": "Head level, eyes lifted upward past the camera in a contemplative look.",
    "shoulder-shrug": "Shoulders lifted in a small shrug, head tilted toward one raised shoulder, looking at the camera.",
    "both-hands-clasped": "Both hands clasped lightly near the chest, shoulders forward, gaze toward the lens.",
    "hand-on-cheek": "One hand resting against her cheek, head tilted into it, eyes on the camera.",
    "lean-toward-camera": "Upper body leaning slightly toward the camera, head level, direct gaze.",
    "lean-back-slight": "Torso leaned back a touch, chin raised, gazing calmly at the lens.",
    "quarter-turn-back": "Body turned a quarter away, head rotated back to face the camera over the shoulder line.",
    "hands-on-hips-waistup": "Hands placed on the hips, shoulders squared, head level and looking forward.",
    "one-shoulder-forward": "One shoulder rolled forward toward the camera, head tilted the opposite way, gaze at the lens.",
    "looking-down-side": "Head turned to the side and tilted down, eyes lowered in a quiet pose.",
    "hand-adjusting-collar": "One hand raised as if adjusting a collar near the shoulder, head turned toward the camera.",
    "soft-side-glance": "Face nearly forward with eyes shifted to a soft side glance away from the lens.",
    "chin-on-hand": "Chin resting on the back of one hand, elbow implied at the waist, gazing at the camera.",
    "head-back-eyes-closed": "Head tilted gently back with a relaxed expression and eyes softly closed.",
    "shoulders-back-open": "Shoulders drawn back and open, chest lifted, head level with a confident forward gaze.",
    "turn-right-look-back": "Body turned to the right with the head swiveled back to meet the camera.",
    "hand-near-jaw": "Fingertips lightly grazing the jawline, head tilted slightly, eyes toward the lens.",
    "tilt-forward-brow": "Head tipped slightly forward, brow toward the camera, eyes lifted to the lens.",
    "relaxed-neutral-straight": "Neutral upright posture, shoulders even, head straight, gazing steadily at the camera.",
    "look-up-and-away": "Head turned upward and to the side, gaze lifted away from the camera thoughtfully.",
    "crossed-arms-turned": "Arms folded across the chest with the body angled sideways, head turned to the camera.",
    "hand-on-shoulder": "One hand reaching across to rest on the opposite shoulder, head tilted, looking forward.",
    "gentle-head-drop": "Head dropped gently to one side with a relaxed neck, eyes toward the camera.",
    "three-quarter-left-down": "Body three-quarters to the left with head slightly lowered, gaze angled at the lens.",
    "both-hands-to-hair": "Both hands raised to gather hair behind the head, chin lifted, gaze forward.",
    "shoulder-dip-tilt": "One shoulder dipped low, head tilted toward the lifted side, looking at the camera.",
    "straight-serene": "Upright and still, shoulders square, head level with a serene direct gaze.",
    "turning-away-glance": "Mid-turn away from the camera with the head glancing back briefly toward the lens.",
    "hand-under-chin": "One hand cupped lightly under the chin, elbow low, head tilted, eyes on the camera.",
    "look-over-low-shoulder": "Shoulders lowered and relaxed, head turned to look back over one shoulder softly.",
    "tilt-and-touch-ear": "One hand lifted near the ear, head tilted toward that hand, gaze directed at the camera.",
    "forward-lean-hands-clasped": "Leaning forward slightly with hands clasped near the chest, head level, looking at the lens."
  },
  "Standing": {
    "contrapposto-hand-hip": "Standing with weight shifted onto her right leg, left knee softly bent, one hand resting on her hip while the other hangs loosely at her side, head turned toward the camera.",
    "arms-crossed-relaxed-2": "Standing tall with feet hip-width apart, arms crossed comfortably over her chest, chin slightly lifted and gaze directed at the camera.",
    "both-hands-pockets": "Weight evenly balanced, both hands tucked into imagined pockets, shoulders relaxed, looking off to her left.",
    "hand-behind-neck-2": "Standing with weight on her left leg, right arm raised so her hand rests at the back of her neck, other arm relaxed, head tilted slightly.",
    "clasped-front": "Upright stance with feet together, hands loosely clasped in front of her waist, gaze lowered toward her hands.",
    "side-profile-look-back": "Body turned to her side in profile, weight on the back foot, looking back over her shoulder toward the camera.",
    "one-arm-across-waist": "Standing with one arm wrapped across her waist supporting the opposite elbow, that hand near her chin, eyes toward the camera.",
    "hands-on-both-hips": "Feet planted shoulder-width apart, both hands firmly on her hips, shoulders squared, looking straight ahead.",
    "reaching-up-stretch": "Standing on the balls of her feet, both arms reaching gently upward overhead, head tilted back slightly.",
    "lean-invisible-wall": "Leaning her shoulder against an unseen wall with legs crossed at the ankles, one hand resting on her thigh, looking toward the camera.",
    "three-quarter-turn": "Body angled three-quarters away, weight on the far leg, near hand resting lightly on her hip, glancing back toward the camera.",
    "hair-tuck": "Standing with weight on one hip, one hand raised to tuck hair behind her ear, other arm relaxed, gaze soft and downward.",
    "arms-loose-sides": "Neutral upright stance, feet parallel, both arms hanging naturally at her sides, looking directly toward the camera.",
    "hands-clasped-behind": "Standing straight with hands clasped behind her back, shoulders drawn slightly back, chin level and gaze forward.",
    "crossed-ankles-front": "Standing with ankles crossed and weight distributed lightly, both hands resting in front of her thighs, head tilted to one side.",
    "one-hand-collarbone": "Weight shifted to her right leg, one hand resting gently at her collarbone, the other along her side, looking away thoughtfully.",
    "twist-torso": "Hips facing forward while her torso twists gently to one side, arms following the turn, head following the twist.",
    "foot-forward-pose": "One foot stepped forward with weight on the back leg, hands lightly clasped at waist level, gaze toward the camera.",
    "both-hands-nape": "Standing upright with both hands lifted to the nape of her neck, elbows out, head tilted slightly upward.",
    "casual-lean-back": "Leaning slightly back with weight on both heels, arms folded low across her stomach, looking off to the side.",
    "hand-on-thigh": "Standing with weight on one leg, one hand resting flat against her thigh, other arm relaxed, chin turned gently downward.",
    "shoulder-shrug-2": "Standing with shoulders raised in a light shrug, hands turned palm-up near her hips, looking toward the camera.",
    "crossed-arms-shoulder-drop": "Arms crossed with one shoulder dropped lower, weight shifted onto that same hip, gaze angled away.",
    "reach-across-shoulder": "Standing tall with one arm reaching across to touch the opposite shoulder, other arm at her side, head level.",
    "palms-together-chest": "Upright stance with palms pressed lightly together near her chest, elbows relaxed, eyes closed calmly.",
    "wide-stance-hands-hips": "Feet set wide in a grounded stance, both hands on her hips, chin lifted confidently toward the camera.",
    "looking-up-hand-heart": "Standing with one hand resting over her heart, weight even, head tilted upward with a soft upward gaze.",
    "turn-away-glance": "Turned mostly away from the camera, hands resting at her sides, head turning back for a subtle glance.",
    "single-arm-raised-wave": "Standing with one arm raised at shoulder height in a gentle wave, other hand on her hip, looking toward the camera.",
    "crossed-legs-standing": "Standing with one leg crossed over the other, hands clasped loosely in front, head tilted slightly to the side.",
    "hand-under-chin-2": "Weight on one hip, one elbow supported by the opposite hand, that hand resting under her chin, gazing off thoughtfully.",
    "both-arms-behind-lean": "Leaning back slightly with both arms held behind her, hands resting at her lower back, looking forward.",
    "step-and-pivot": "Mid-step stance with weight transferring forward, torso pivoting, one arm swinging naturally, head facing the camera.",
    "gentle-forward-lean": "Leaning her upper body gently forward from the hips, hands resting on her thighs, gaze directed toward the camera.",
    "arms-open-slight": "Standing upright with arms held slightly open and away from her body, palms forward, looking straight ahead.",
    "hand-shading-eyes": "Standing with one hand raised to shade her eyes, other hand on her hip, gazing into the distance.",
    "cross-body-hold": "Standing with one arm reaching across her body to hold the opposite arm near the elbow, head tilted downward.",
    "heel-lift-pose": "Standing with one heel lifted and knee slightly bent, hands loosely at her sides, glancing over her shoulder.",
    "both-hands-back-hair": "Standing tall with both hands lifted into her hair sweeping it back, elbows raised, chin lifted slightly.",
    "weight-back-relaxed": "Weight settled onto her back leg with front leg extended forward, arms relaxed, looking calmly toward the camera.",
    "one-hand-neck-other-hip": "Standing with one hand resting on the side of her neck and the other on her hip, head tilted toward the raised shoulder.",
    "folded-hands-lowered-gaze": "Upright with hands folded gently at waist height, shoulders relaxed, eyes lowered in a quiet expression.",
    "quarter-turn-camera": "Body turned a quarter toward the camera, weight on the near foot, hands loosely at her sides, gaze meeting the lens.",
    "raised-elbow-lean": "Standing with one elbow raised as if resting on an unseen ledge, other hand on her hip, looking toward the camera.",
    "symmetrical-front": "Perfectly upright symmetrical stance, feet together, arms straight at her sides, gaze forward and level.",
    "twist-look-down": "Torso twisted slightly with one hand on the opposite hip, head turned and tilted downward toward her shoulder.",
    "hands-clasped-overhead": "Standing with hands clasped together and stretched above her head, weight evenly balanced, chin gently raised.",
    "lean-forward-hands-knees": "Bending slightly forward with hands resting on her knees, back straight, looking up toward the camera.",
    "arm-drape-front": "Standing with one arm draped loosely across the front of her body, hand resting on the opposite hip, gaze to the side.",
    "confident-stride-stop": "Standing as if just paused mid-stride, one foot ahead, hands relaxed and slightly swept back, looking toward the camera."
  },
  "Walking & Motion": {
    "mid-stride-forward": "She walks straight toward the camera mid-stride, one foot lifted off the ground, arms swinging naturally at her sides, gaze fixed ahead.",
    "turning-over-shoulder": "She strides away from the camera but twists her torso to glance back over her right shoulder, one hand resting lightly on her hip.",
    "spinning-arms-out": "She spins on the ball of one foot with both arms extended outward and her head tilted back slightly, hair swinging around her.",
    "hair-caught-wind": "She stands with weight on her back leg, one hand lifted toward her flying hair, chin turned into the breeze.",
    "long-stride-side": "She takes a long lunging step to the side, front knee bent, trailing arm sweeping back, looking in the direction she moves.",
    "walking-hand-hair": "She walks in profile to the camera, one hand tucking a strand of hair behind her ear, the other loose at her side.",
    "pivot-mid-turn": "She pivots mid-turn with her upper body facing left and hips still square, arms crossing loosely in front of her.",
    "skipping-step": "She rises into a light skip, one knee raised high and both hands slightly out for balance, looking upward.",
    "striding-confident": "She strides confidently toward the camera with shoulders back, one hand swinging forward and the other trailing behind.",
    "twirl-fabric": "She twirls with her arms held low, letting fabric flare around her legs, head turned to follow the motion.",
    "stepping-off-curb": "She steps down as if off a curb, one foot lower than the other, one arm reaching slightly forward for balance.",
    "looking-back-walk": "She walks away with her back to the camera, head turned to glance over her left shoulder toward the lens.",
    "mid-run": "She breaks into a light run, both arms bent at the elbows and pumping, one foot pushing off the ground, eyes forward.",
    "turning-toward-camera": "She turns her whole body toward the camera mid-step, front foot planted, one hand raised in a small casual wave.",
    "walking-hands-pockets": "She strolls forward with both hands tucked into her pockets, shoulders relaxed, gaze drifting to one side.",
    "leaning-into-turn": "She leans into a sharp turn with her outer arm swinging wide and inner shoulder dropped, looking around the curve.",
    "sideways-glance-stride": "She walks past the camera in profile, giving a quick sideways glance toward the lens without stopping.",
    "jump-mid-air": "She leaps upward with both feet off the ground, knees slightly bent and arms lifted, chin up toward the sky.",
    "gathering-skirt-walk": "She walks briskly while gathering fabric to one side with one hand, the other arm swinging, looking down slightly.",
    "spin-hair-fanning": "She completes a fast spin so her hair fans outward in a wide arc, arms tucked close, face turning toward the camera.",
    "stepping-over": "She lifts one leg high to step over something, arms spread for balance, gaze focused downward at her path.",
    "walking-arms-swinging": "She walks diagonally across the frame with both arms swinging in full opposition to her legs, looking straight ahead.",
    "turn-hand-on-hip": "She stops mid-turn with one hand landing on her hip, the other arm relaxed, head cocked toward the camera.",
    "backward-step": "She takes a playful step backward, one arm reaching forward and the other back, gaze locked on the camera.",
    "walking-looking-up": "She strolls forward with her face tilted upward, one hand shading her brow, the other swinging gently.",
    "quick-pivot-glance": "She pivots quickly on one heel with arms crossing her body, throwing a glance over her shoulder toward the lens.",
    "striding-scarf-flying": "She strides forward as trailing fabric streams behind her, one hand lifted near her collar, eyes ahead.",
    "mid-step-pause": "She pauses mid-step with one foot suspended just above the ground, both hands loosely clasped in front, looking down.",
    "twist-and-walk": "She walks forward while twisting her upper body to look behind her, one arm wrapping across her waist.",
    "skipping-sideways": "She hops sideways with feet close together, arms swinging in unison, head turned in her direction of travel.",
    "dynamic-lunge-step": "She drops into a deep forward lunge as if lunging into a stride, back arm swept high, gaze forward and low.",
    "walking-hand-on-neck": "She walks slowly with one hand resting on the back of her neck, elbow raised, the other arm swinging, looking sideways.",
    "turning-full-circle": "She rotates through a full turn with arms slightly raised and hair swinging, momentarily glancing at the camera.",
    "rushing-forward": "She rushes forward with a long urgent stride, both arms reaching ahead, focus fixed in the distance.",
    "casual-saunter": "She saunters loosely with a slight sway, one hand toying with her hair and the other resting at her side, looking off-camera.",
    "stepping-up": "She steps up onto a higher level, one knee lifted and one hand reaching forward as if to steady herself, eyes up.",
    "walking-arms-folded": "She walks forward with arms folded across her chest, shoulders slightly hunched, gaze lowered thoughtfully.",
    "whirl-look-down": "She whirls around with skirt flaring, arms trailing behind, and her head tipped down watching the fabric move.",
    "striding-both-hands-up": "She strides energetically with both hands lifted near shoulder height, palms open, looking straight toward the camera.",
    "tiptoe-step": "She rises onto her tiptoes mid-step, arms extended outward for balance, chin lifted and gaze forward.",
    "walking-away-glance-down": "She walks away from the camera with head bowed, one hand brushing her hair back over her shoulder.",
    "crossing-legs-walk": "She takes a crossing step with one leg passing in front of the other, hips swaying, one arm out for balance.",
    "quick-turn-hair-swing": "She turns her head sharply so her hair swings across her face, torso still mid-stride, one hand rising to catch it.",
    "marching-step": "She marches forward with a high knee lift and swinging opposite arm, back straight, eyes level ahead.",
    "leaning-run-start": "She leans forward into the start of a run, both arms cocked back, one foot digging in, gaze fixed far ahead.",
    "gliding-step-side": "She glides one foot to the side in a smooth lateral step, arms floating slightly outward, head following the motion.",
    "walking-looking-down-phone": "She walks slowly with her head tilted down toward her cupped hands, one elbow tucked in, steps small and measured.",
    "spin-stop-pose": "She halts abruptly from a spin, one arm flung out and the other across her middle, hair settling, looking at the camera.",
    "strolling-hands-behind": "She strolls forward with both hands clasped behind her back, chin up, gaze wandering slightly to one side.",
    "leaping-step-over-puddle": "She takes a broad leaping step forward as if clearing a gap, arms swept back, both feet briefly airborne, eyes down on her landing."
  },
  "Sitting": {
    "chair-hands-lap": "Seated upright on a chair with knees together, both hands resting folded in her lap, looking toward the camera.",
    "stool-legs-crossed": "Perched on a stool with legs crossed at the knee, one hand on her thigh and the other resting on the seat edge, gazing to the side.",
    "bench-lean-back": "Sitting on a bench leaning back with both arms stretched along the backrest, head tilted slightly upward.",
    "steps-elbows-knees": "Seated on a step with feet apart, elbows resting on her knees and hands loosely clasped, looking down.",
    "ledge-side-lean": "Sitting on a ledge with weight leaned onto one hand behind her, the other hand resting on her thigh, turning her head over her shoulder.",
    "table-edge-perch": "Perched lightly on the edge of a table with feet dangling, both hands gripping the edge beside her, looking toward the camera.",
    "chair-turned-side": "Sitting sideways on a chair with one arm draped over the backrest, head turned to face forward.",
    "floor-knees-hugged": "Seated on the floor with knees drawn up and both arms wrapped around her shins, chin resting on her knees.",
    "stool-feet-rung": "Sitting on a tall stool with feet on the footrest rung, hands resting on her knees, looking straight ahead.",
    "bench-crossed-ankles": "Seated on a bench with ankles crossed and hands placed flat on either side of her hips, head level and eyes forward.",
    "steps-lean-back-hands": "Sitting on steps reclining onto both hands placed behind her, legs extended down the stairs, gazing upward.",
    "chair-lean-forward": "Leaning forward in a chair with forearms on her thighs and hands loosely together, looking down and to the side.",
    "ledge-legs-dangle": "Sitting on a high ledge with both legs hanging freely, hands resting in her lap, turning to look over her shoulder.",
    "floor-side-sit": "Sitting on the floor in a side-saddle position with legs folded to one side, one hand on the ground for support and the other on her hip.",
    "table-cross-legged": "Sitting cross-legged on a table with both hands resting on her ankles, looking toward the camera.",
    "chair-arm-rest": "Seated in an armchair with elbows on the armrests and fingers lightly interlaced, head tilted slightly to one side.",
    "stool-one-foot-down": "Perched on a stool with one foot on the ground and the other on the rung, one hand on her knee, gazing to the left.",
    "bench-shoulder-turn": "Sitting on a bench with body angled and one shoulder forward, hands clasped in her lap, looking toward the camera.",
    "steps-side-profile": "Seated on a step in profile with knees bent, one arm resting across her knees, head turned forward.",
    "floor-legs-extended": "Sitting on the floor with legs extended straight in front, leaning back on both palms, chin lifted slightly.",
    "chair-hand-chin": "Seated on a chair with one elbow propped on the backrest and a hand near her chin, looking away thoughtfully.",
    "ledge-both-hands-behind": "Sitting on a ledge with both hands planted behind for support, chest open and head tilted back gently.",
    "stool-hands-thighs": "Sitting squarely on a stool with knees apart, both hands resting on her thighs, looking directly toward the camera.",
    "bench-cross-lean": "Seated on a bench with legs crossed and torso leaning to one side onto a hand pressed to the seat, gazing sideways.",
    "steps-hands-clasped": "Sitting on steps with feet on a lower step, hands clasped around one knee, looking off to the distance.",
    "floor-kneel-sit": "Kneeling and sitting back on her heels on the floor, hands resting palm-down on her thighs, head level.",
    "chair-backwards-straddle": "Sitting facing the back of a chair with arms folded over the top rail and chin resting on her forearms.",
    "table-lean-hand": "Perched on a table edge leaning onto one straightened arm, the other hand resting in her lap, looking toward the camera.",
    "ledge-knee-up": "Sitting on a ledge with one knee drawn up and an arm wrapped around it, the other leg hanging down, gazing to the side.",
    "stool-crossed-arms": "Seated on a stool with arms loosely crossed over her middle, feet on the rung, head turned slightly right.",
    "bench-hands-behind-head": "Sitting relaxed on a bench with both hands laced behind her head and elbows out, looking upward.",
    "steps-lean-rail": "Seated on steps leaning her shoulder toward an unseen rail, one hand resting on the step beside her, looking forward.",
    "floor-one-knee-up": "Sitting on the floor with one leg folded flat and the other knee raised, resting an arm across the raised knee, looking down.",
    "chair-legs-to-side": "Sitting on a chair with both legs angled to one side and ankles together, hands resting on the nearer thigh, gazing over her shoulder.",
    "ledge-relaxed-slouch": "Sitting on a ledge in a relaxed slouch with hands resting loosely between her knees, head lowered slightly.",
    "stool-turn-shoulder": "Perched on a stool with torso rotated so one shoulder leads, a hand on the seat behind her, looking back toward the camera.",
    "bench-feet-tucked": "Sitting on a bench with both feet tucked up beside her, one hand supporting on the seat, the other in her lap.",
    "table-legs-crossed-lean": "Sitting on a table with legs crossed and leaning back on both hands, head tilted casually to one side.",
    "steps-arms-wrapped": "Seated on a step with knees together and both arms wrapped around her legs, resting her cheek toward her knees while looking forward.",
    "floor-lean-elbow": "Reclining on the floor propped on one elbow with legs stretched to the side, the free hand resting on her hip, gazing forward.",
    "chair-upright-alert": "Sitting upright at the front edge of a chair with feet flat and hands gripping the seat sides, looking attentively toward the camera.",
    "ledge-hands-in-lap": "Sitting on a ledge with knees together and both hands folded neatly in her lap, head tilted gently to one side.",
    "stool-back-arch": "Perched on a stool sitting tall with a slight back arch, both hands resting behind her on the seat, chin lifted.",
    "bench-look-down-hands": "Seated on a bench looking down at her hands cupped together in her lap, shoulders relaxed.",
    "steps-one-hand-up": "Sitting on steps with one hand resting on a higher step and the other on her knee, turning her head toward the camera.",
    "floor-cross-legged-straight": "Sitting cross-legged on the floor with a straight back and hands resting on her knees, looking forward calmly.",
    "chair-side-glance": "Seated on a chair with hands resting one atop the other on her lap, body facing forward but head turned in a soft side glance.",
    "table-perch-feet-up": "Perched on a table with one foot resting on a nearby chair and hands clasped around that raised knee, gazing to the side.",
    "ledge-lean-forward-elbows": "Sitting on a ledge leaning forward with elbows on her knees and fingers interlocked, looking straight toward the camera.",
    "bench-recline-arms-spread": "Sitting low on a bench with both arms spread wide along the backrest and legs casually extended, head turned to one side."
  },
  "Floor & Ground": {
    "cross-legged-upright": "Sitting cross-legged on the floor with a straight back, hands resting on her knees, looking toward the camera.",
    "side-hip-lean": "Sitting with both legs folded to one side, one hand pressed to the floor for support, gazing softly off to the side.",
    "knees-hugged": "Sitting on the ground hugging both knees to her chest with clasped arms, chin lifted slightly toward the camera.",
    "leaning-back-hands": "Leaning back with both palms planted on the floor behind her, legs extended forward, face turned upward.",
    "kneeling-tall": "Kneeling upright with knees together, hands resting on the tops of her thighs, looking straight ahead.",
    "kneeling-heels": "Kneeling and sitting back on her heels, both hands folded in her lap, head tilted gently to one side.",
    "one-knee-up": "Sitting with one knee raised and the other leg folded flat, one forearm draped over the raised knee, looking toward the camera.",
    "legs-extended-forward": "Sitting with both legs extended straight forward, hands resting lightly at her sides, gaze directed ahead.",
    "side-recline-elbow": "Reclining on her side propped up on one elbow, other hand resting on her hip, looking toward the camera.",
    "seated-lean-forward": "Sitting with legs crossed and leaning forward slightly with forearms on her knees, head lowered a touch, eyes up.",
    "kneel-lean-side": "Kneeling with weight shifted to one hip, one hand on the floor and the other on her thigh, glancing over her shoulder.",
    "knees-bent-feet-flat": "Sitting with knees bent and feet flat on the floor, arms wrapped loosely around her shins, looking to the side.",
    "back-arch-hands-behind": "Sitting upright with both hands clasped behind her back, shoulders drawn back, chin level toward the camera.",
    "prone-elbows-up": "Lying on her front with both elbows propped up and chin resting in her hands, feet lifted behind her.",
    "seated-twist": "Sitting on the floor with legs folded, torso twisted to one side, one hand on the opposite knee, looking back.",
    "kneel-hands-thighs": "Kneeling with a gentle sway to her posture, both hands resting on her thighs, gaze soft and lowered.",
    "cross-ankles-lean": "Sitting with ankles crossed and legs extended, leaning on one straight arm to the floor, head turned to the camera.",
    "seated-arms-crossed": "Sitting cross-legged with arms folded across her chest, chin lifted and eyes looking forward.",
    "knees-side-hand-hair": "Sitting with legs tucked to one side, one hand raised to touch her hair, other resting on the floor, looking away.",
    "long-sit-lean-back": "Sitting with legs stretched forward and leaning back on both elbows, head tilted upward and relaxed.",
    "kneel-one-hand-floor": "Kneeling on both knees with one hand lightly touching the floor beside her, the other on her lap, glancing sideways.",
    "tuck-legs-clasp": "Sitting with both legs tucked under her and hands clasped in her lap, back straight, looking toward the camera.",
    "side-sit-arm-drape": "Sitting side-saddle with one arm draped across her raised knee, the other supporting her on the floor, gazing ahead.",
    "seated-hands-lap": "Sitting cross-legged with hands resting gently in her lap, shoulders relaxed, head slightly bowed.",
    "floor-lean-one-arm": "Sitting with knees drawn to one side and leaning on one extended arm, free hand on her knee, looking off-camera.",
    "kneel-reach-forward": "Kneeling and reaching both hands forward to rest lightly on the floor ahead, head lifted toward the camera.",
    "seated-both-hands-back": "Sitting with legs extended and both hands planted behind her, leaning back with face turned to one side.",
    "crossed-legs-chin-hand": "Sitting cross-legged resting her chin in one hand with the elbow on her knee, eyes toward the camera.",
    "side-recline-full": "Reclining fully on her side with legs stacked, head propped on a bent arm, looking calmly forward.",
    "knees-up-both-hands": "Sitting with both knees raised and both hands resting on top of them, gaze directed slightly downward.",
    "kneel-back-straight-look-up": "Kneeling tall with hands loosely at her sides and face lifted upward toward the light.",
    "seated-lean-one-side": "Sitting with legs folded and leaning her weight into one hip, resting head lightly on her shoulder, looking ahead.",
    "floor-hands-behind-legs-cross": "Sitting with crossed legs and both hands braced flat behind her, torso open, glancing to the side.",
    "kneel-hands-clasped-lap": "Kneeling back on her heels with hands clasped in her lap, head tilted gently and eyes toward the camera.",
    "seated-arm-over-knee": "Sitting with one knee up and one leg flat, resting one arm over the raised knee, other hand on the floor, looking away.",
    "prone-hands-chin": "Lying on her stomach with both hands cupped under her chin, looking straight toward the camera.",
    "seated-hug-one-knee": "Sitting with one knee hugged to her chest and the other leg extended, chin resting near her knee, gaze soft.",
    "kneel-turn-shoulder": "Kneeling with body angled away and head turned back over her shoulder toward the camera, hands on thighs.",
    "long-sit-hands-lap": "Sitting with legs stretched forward and hands folded gently in her lap, back upright, looking ahead.",
    "side-sit-both-hands-floor": "Sitting to one side with both hands resting on the floor beside her hip, head tilted, gazing off-frame.",
    "cross-legged-lean-forward": "Sitting cross-legged and leaning forward slightly with hands resting on her ankles, eyes toward the camera.",
    "kneel-one-knee-raised": "Kneeling on one knee with the other foot planted flat, forearm resting on the raised knee, looking forward.",
    "seated-back-to-camera": "Sitting on the floor with her back mostly to the camera, one hand on the floor, head turned to glance back.",
    "knees-folded-hands-side": "Sitting with knees folded neatly beneath her and hands resting on the floor at either side, chin level.",
    "floor-recline-knees-bent": "Reclining back on both elbows with knees bent and feet flat, head relaxed and turned toward the camera.",
    "seated-fingers-interlaced": "Sitting cross-legged with fingers interlaced around one knee, shoulders relaxed, looking gently to the side.",
    "kneel-hands-behind": "Kneeling upright with both hands clasped behind her back, chest open, gaze lifted forward.",
    "side-sit-lean-hand-cheek": "Sitting with legs tucked aside, resting one hand against her cheek with elbow propped on her knee, looking away.",
    "seated-legs-crossed-loose": "Sitting with ankles loosely crossed and hands resting palm-down on her thighs, head tilted, eyes forward.",
    "floor-arms-wrapped-shins": "Sitting with both feet flat and arms wrapped around her shins, resting chin on knees, looking toward the camera.",
    "kneel-lean-forward-hands-floor": "Kneeling and leaning forward with both palms flat on the floor ahead of her, head raised and gaze soft."
  },
  "Kneeling & Crouching": {
    "kneel-upright-hands-thighs": "Kneeling upright with both knees together, spine tall, hands resting flat on her thighs and head level looking toward the camera.",
    "kneel-back-heels": "Kneeling back on her heels with hands loosely folded in her lap and chin slightly lowered.",
    "kneel-one-up": "Kneeling on one knee with the other foot planted forward, forearm resting on the raised knee and gaze angled to the side.",
    "squat-arms-crossed-knees": "Squatting low with feet flat, forearms crossed over her knees and head turned to look over her shoulder.",
    "crouch-fingertips-ground": "Crouching low with knees bent, fingertips touching the ground for balance and eyes looking straight ahead.",
    "kneel-hands-behind-2": "Kneeling upright with hands clasped loosely behind her back, shoulders open and head tilted gently upward.",
    "kneel-lean-forward": "Kneeling and leaning slightly forward with palms pressed on the floor in front of her, looking down.",
    "kneel-side-sit": "Kneeling with both legs folded to one side, one hand on the floor for support and gaze toward the camera.",
    "squat-hands-clasped": "Squatting balanced on the balls of her feet with hands clasped between her knees and head level.",
    "kneel-reach-up": "Kneeling upright with both arms reaching straight overhead, gaze following her hands upward.",
    "crouch-hug-knees": "Crouching low and hugging both knees to her chest with head resting to one side.",
    "kneel-one-hand-hip": "Kneeling on both knees with one hand on her hip and the other relaxed at her side, looking to the left.",
    "kneel-tall-arms-back": "Kneeling tall with both hands planted on the floor behind her, chest lifted and chin raised.",
    "squat-one-arm-forward": "Squatting with one arm extended forward resting on the raised knee and the other hand on the ground.",
    "kneel-hands-neck": "Kneeling upright with both hands lightly cupped at the back of her neck and head turned slightly right.",
    "kneel-lean-back-hands": "Kneeling back on heels leaning slightly backward on both hands, face turned upward.",
    "crouch-low-balanced": "Crouching in a deep balanced squat with both hands resting on the floor between her feet, looking ahead.",
    "kneel-arms-folded": "Kneeling upright with arms folded across her chest and gaze directed toward the camera.",
    "kneel-reach-side": "Kneeling and reaching one arm out to the side while the other rests on her thigh, head following the reach.",
    "kneel-hands-floor-side": "Kneeling with both hands placed flat on the floor to one side and torso gently twisted that direction.",
    "squat-hands-knees": "Squatting with hands resting on top of both knees, elbows out and head level looking forward.",
    "kneel-one-knee-look-down": "Kneeling on one knee with both hands loosely resting on the forward thigh and eyes lowered.",
    "kneel-shoulder-turn": "Kneeling upright with torso turned to glance over one shoulder and hands relaxed in her lap.",
    "crouch-fingertips-balance": "Crouching low on toes with one hand's fingertips touching the ground and the other arm extended for balance.",
    "kneel-hands-pray": "Kneeling back on heels with palms pressed together at her chest and gaze softly downward.",
    "kneel-lean-forward-elbows": "Kneeling forward with both elbows resting on the ground and forearms flat, head lifted to look ahead.",
    "squat-arms-relaxed": "Squatting comfortably with feet flat and arms hanging relaxed between her knees, looking to one side.",
    "kneel-hair-touch": "Kneeling upright with one hand raised to tuck hair behind her ear and the other on her thigh.",
    "kneel-both-hands-front": "Kneeling with both hands resting flat on the floor directly in front and back slightly rounded.",
    "kneel-side-lean": "Kneeling on both knees leaning her weight onto one supporting hand on the floor beside her, head tilted.",
    "crouch-arms-wrapped": "Crouching low with both arms wrapped around her shins and chin resting near her knees.",
    "kneel-tall-hands-clasped-front": "Kneeling tall with both hands clasped loosely in front at waist height and gaze toward the camera.",
    "kneel-one-up-hand-ground": "Kneeling on one knee with the raised foot planted and one hand pressed to the ground beside it.",
    "squat-look-over-shoulder": "Squatting low with hands together and torso rotated to look over her shoulder.",
    "kneel-arms-out-wide": "Kneeling upright with both arms opened wide to the sides and head tilted slightly back.",
    "kneel-hands-lap-tilt": "Kneeling back on heels with hands folded in her lap and head tilted thoughtfully to one side.",
    "kneel-reach-floor-forward": "Kneeling and reaching both hands forward along the floor with hips settling back toward her heels.",
    "crouch-one-knee-down": "Crouching with one knee lowered to the ground and the other bent, forearm draped over the raised knee.",
    "kneel-hand-chin": "Kneeling upright with one elbow supported on a thigh and hand resting under her chin.",
    "kneel-both-hands-hips": "Kneeling upright with both hands on her hips, shoulders squared and looking straight toward the camera.",
    "squat-hands-floor-forward": "Squatting low with both hands reaching to the floor in front and gaze fixed downward.",
    "kneel-twist-look-back": "Kneeling upright with torso twisted at the waist to look behind her, hands resting on thighs.",
    "kneel-lean-one-side": "Kneeling with legs folded to one side and one hand resting on the hip, gaze soft toward the side.",
    "crouch-elbows-knees": "Crouching low with both elbows resting on her knees and hands loosely clasped, looking ahead.",
    "kneel-stretch-arm-overhead": "Kneeling upright with one arm stretched overhead and the other hand on the floor for balance.",
    "kneel-hands-behind-head-look-up": "Kneeling upright with both hands laced behind her head and chin lifted, gazing upward.",
    "squat-balanced-hands-together": "Squatting balanced on flat feet with hands pressed together low between her knees, head level.",
    "kneel-rest-heels-arms-side": "Kneeling back on heels with both arms relaxed down at her sides and head turned gently to the right.",
    "kneel-forward-one-hand-reach": "Kneeling and reaching one hand forward toward the ground while the other steadies on her knee.",
    "crouch-low-gaze-camera": "Crouching low with knees bent, forearms resting across her thighs and eyes looking toward the camera."
  },
  "Lying Down": {
    "side-head-propped": "Lying on her side with elbow bent and head resting on her hand, other arm draped along her hip, looking toward the camera.",
    "back-arms-behind-head": "Lying flat on her back with both hands laced behind her head, elbows out, gazing up at the ceiling.",
    "front-chin-on-hands": "Lying on her front propped on both forearms with chin resting on stacked hands, looking straight ahead.",
    "side-knees-tucked": "Curled on her side with knees drawn up and both hands tucked near her cheek, eyes toward the camera.",
    "back-knees-bent": "On her back with knees bent and feet flat, arms relaxed at her sides, head turned to one side.",
    "prop-elbow-legs-crossed": "Reclining on one elbow with legs extended and crossed at the ankles, free hand resting on her waist, looking to the side.",
    "front-legs-up": "Lying on her stomach with lower legs raised and ankles crossed, propped on forearms, glancing back over her shoulder.",
    "back-one-arm-across": "On her back with one arm across her stomach and the other stretched above her head, looking upward.",
    "side-arm-extended": "Lying on her side with the lower arm extended straight above her head and the top hand resting on the floor in front, gazing forward.",
    "back-hands-on-stomach": "Flat on her back with both hands folded gently on her stomach, head tilted slightly toward the camera.",
    "front-cheek-down": "Lying on her front with one cheek resting on the surface and arms loosely bent beside her head, eyes closed.",
    "side-top-knee-forward": "On her side with the top knee bent forward and lower leg straight, top hand resting on the floor, looking toward the camera.",
    "back-arms-spread": "On her back with both arms spread out wide and relaxed, legs straight, gaze up and slightly to one side.",
    "prop-both-elbows": "Lying on her front propped up on both elbows with hands loosely clasped, head lifted and looking ahead.",
    "side-hand-on-hip": "Reclining on her side, propped on one elbow, with the top hand resting on her hip, looking over toward the camera.",
    "back-knees-up-hands-clasped": "On her back with knees raised and hands clasped over them, chin tucked slightly toward her chest.",
    "front-reaching-forward": "Lying on her stomach with both arms reaching forward along the surface, head lowered, looking down.",
    "side-relaxed-drape": "On her side with the lower arm bent under her head and top arm draped along her side, legs gently stacked, gazing softly ahead.",
    "back-one-knee-raised": "Flat on her back with one knee raised and the other leg straight, one arm resting above her head, looking at the camera.",
    "front-shoulder-turn": "Lying on her front with upper body twisted slightly, one hand near her shoulder, glancing back over her shoulder.",
    "side-both-hands-cheek": "Curled on her side with both palms pressed together beneath her cheek, knees softly bent, eyes toward the camera.",
    "back-legs-crossed-up": "On her back with legs raised and crossed in the air, hands resting flat at her sides, looking upward.",
    "prop-elbow-hand-hair": "Reclining on one elbow with the free hand raised toward her hair, legs extended, looking off to the side.",
    "front-ankles-crossed-flat": "Lying flat on her stomach with arms folded under her chest and ankles crossed, chin resting on her arms, looking ahead.",
    "side-arm-over-head": "On her side with the top arm curved over her head and lower hand resting near her chest, gazing softly toward the camera.",
    "back-hands-behind-neck": "On her back with both hands cradling the back of her neck, elbows relaxed outward, looking up.",
    "side-leg-extended-toe": "Lying on her side with the top leg extended long and toes pointed, propped on one elbow, looking down the length of her body.",
    "front-head-lifted-hands-flat": "On her stomach with hands flat on the surface pushing her upper body slightly up, head lifted and looking forward.",
    "back-arm-over-eyes": "Flat on her back with one forearm resting lightly across her forehead, other arm at her side, head tilted away.",
    "side-knees-stacked-hand-forward": "On her side with knees neatly stacked and the top hand reaching forward on the floor, looking toward the camera.",
    "prop-both-hands-under-chin": "Lying on her front propped on elbows with both hands cupping her chin, head level, gazing ahead.",
    "back-stretch-full": "On her back stretched fully with both arms overhead and toes pointed, looking upward with a relaxed expression.",
    "side-hand-on-shoulder": "Reclining on her side propped on one elbow with the top hand resting on her opposite shoulder, looking to the side.",
    "front-crossed-arms-rest": "Lying on her stomach with arms crossed in front and chin resting on top, eyes toward the camera.",
    "back-one-hand-chest": "On her back with one hand resting lightly over her collarbone and the other along her side, head turned toward the camera.",
    "side-lower-arm-forward": "On her side with the lower arm extended forward and the top hand resting on it, knees slightly bent, gazing ahead.",
    "back-feet-flat-arms-up": "On her back with feet flat and knees bent, both arms raised and hands resting near her head, looking up.",
    "front-turned-hip": "Lying mostly on her front with one hip turned slightly, propped on a forearm, glancing over her shoulder toward the camera.",
    "side-both-arms-forward": "On her side with both arms extended forward together and legs gently curled, looking down along her arms.",
    "back-relaxed-neutral": "Flat on her back with arms loosely at her sides and legs straight, head resting square, gazing straight up.",
    "prop-elbow-knee-up": "Reclining on one elbow with the near knee bent upward and free hand resting on that knee, looking toward the camera.",
    "front-legs-apart-relaxed": "On her stomach with legs relaxed and slightly apart, arms folded beneath her head, cheek resting sideways.",
    "side-hand-trailing-floor": "On her side with the top hand trailing down toward the floor, lower arm under her head, looking softly ahead.",
    "back-crossed-ankles-hands-side": "On her back with ankles crossed and hands resting flat at her sides, head tilted slightly toward the camera.",
    "side-fetal-loose": "Loosely curled on her side with knees drawn up and arms folded in front of her chest, eyes closed.",
    "front-arms-back": "Lying on her stomach with both arms bent back along her sides, cheek down, looking to one side.",
    "back-knee-crossed-over": "On her back with one knee crossed over the other and hands clasped on her stomach, looking up and to the side.",
    "prop-side-book-rest": "On her side propped on one elbow with the top hand resting on the surface as if turning a page, looking downward.",
    "side-top-arm-extended-up": "On her side with the top arm reaching straight upward and lower arm supporting her head, gazing toward the camera.",
    "back-arms-crossed-chest": "Flat on her back with arms crossed over her chest and legs straight, head resting level, looking upward."
  },
  "Leaning": {
    "shoulder-against-wall": "She leans one shoulder against the wall, weight shifted onto the near foot, arms loosely crossed, head turned toward the camera.",
    "back-flat-wall": "She stands with her back flat against the wall, both hands resting behind her lower back, chin lifted slightly and gaze forward.",
    "elbow-on-railing": "She rests one forearm along a railing, hips angled away, the other hand hanging at her side, looking off to the left.",
    "both-hands-railing": "She grips a railing with both hands and leans back from it, arms straight, head tilted slightly and eyes toward the camera.",
    "doorway-lean": "She leans a shoulder into a doorway frame, one hand raised to touch the jamb above, weight on one hip, glancing sideways.",
    "doorframe-both-hands": "She stands in a doorway with both hands pressed to the frame at shoulder height, leaning forward slightly, looking straight ahead.",
    "pillar-back-lean": "She leans her back against a round pillar, hands clasped in front of her, one knee bent with the foot flat on the pillar behind.",
    "pillar-side-lean": "She rests her side against a pillar, one arm wrapped loosely around it, head resting near the surface, gazing softly downward.",
    "counter-hip-lean": "She leans her hip against a counter, one hand resting on the edge, the other arm relaxed, looking toward the camera.",
    "counter-both-elbows": "She rests both elbows on a counter behind her, leaning back, ankles crossed, head turned to one side.",
    "car-door-lean": "She leans a shoulder and hip against a car door, arms folded, weight on the near leg, looking away over her shoulder.",
    "car-hood-lean": "She leans back against a car hood with both palms flat on it, arms straight, gaze lifted toward the camera.",
    "wall-one-hand-flat": "She stands beside a wall with one palm flat against it, elbow bent, torso angled inward, head lowered thoughtfully.",
    "wall-forearm-rest": "She rests a forearm against the wall above her head, leaning into it, the other hand on her hip, looking to the side.",
    "railing-back-lean": "She leans her lower back against a railing, both hands lightly gripping it on either side, ankles crossed, facing forward.",
    "wall-crossed-ankles": "She leans her back on the wall with ankles crossed and arms folded loosely, head tilted, gaze drifting to one side.",
    "counter-turn-toward": "She leans one hip on a counter and turns her upper body toward the camera, one hand on the surface, other on her thigh.",
    "pillar-hand-behind": "She stands with her back to a pillar, one hand tucked behind it, the other at her side, chin dropped and eyes down.",
    "doorway-relaxed": "She leans casually in a doorway, one shoulder resting on the frame, hands loosely in front, looking toward the camera.",
    "wall-seated-lean": "She sits low against the base of a wall, back supported, knees bent, arms draped over her knees, head turned to the side.",
    "railing-elbows-back": "She hooks both elbows over a railing behind her, leaning her weight into it, chest open, gazing upward slightly.",
    "car-side-mirror": "She rests a hand near a car's side mirror while leaning her hip on the door, other arm relaxed, looking ahead.",
    "wall-shoulder-glance": "She presses a shoulder blade to the wall, turning her head over that shoulder to glance back toward the camera.",
    "counter-lean-forward": "She leans forward onto a counter with both forearms resting flat, weight shifted forward, head lifted and gaze soft.",
    "pillar-lean-arms-crossed": "She leans her back against a pillar with arms crossed and one foot propped behind her, head level and eyes forward.",
    "wall-hands-behind-back": "She stands against a wall with both hands pressed behind her lower back, shoulders relaxed, chin slightly raised.",
    "railing-one-elbow": "She rests one elbow on a railing and leans her cheek lightly against that hand, the other arm hanging loose, looking down.",
    "doorway-back-lean": "She leans her back against one side of a doorway, hands loosely clasped at her waist, one knee slightly bent.",
    "car-lean-arms-folded": "She leans back against the side of a car with arms folded across her chest, feet crossed at the ankles, gazing to the side.",
    "wall-tilt-head": "She leans a shoulder to the wall and tilts her head to rest against it, arms loose at her sides, eyes toward the camera.",
    "counter-back-rest": "She rests her back against a counter edge, both hands gripping it beside her hips, one foot forward, looking ahead.",
    "pillar-forward-lean": "She places both hands on a pillar and leans forward slightly with straight arms, head lowered, gaze toward her hands.",
    "railing-hip-turn": "She leans her hip on a railing and turns her torso to face it, one hand resting on top, the other on her waist.",
    "wall-single-shoulder": "She rests a single shoulder against the wall, near arm hanging, far hand tucked into her side, looking off to the right.",
    "doorway-arms-overhead": "She stands in a doorway with both hands reaching up to grip the frame overhead, leaning slightly forward, gaze ahead.",
    "car-lean-one-hand": "She leans her back on a car with one hand resting flat on the surface behind her, the other relaxed, head turned aside.",
    "counter-elbow-cheek": "She leans an elbow on a counter and rests her chin lightly on her knuckles, the other arm across her lap, looking down.",
    "wall-knee-up": "She leans her back on the wall with one foot flat against it and knee raised, hands at her sides, gazing forward.",
    "railing-both-arms-drape": "She drapes both arms over a railing in front of her, leaning her weight onto it, head slightly bowed and eyes soft.",
    "pillar-cheek-rest": "She rests her cheek and shoulder against a pillar, arms folded softly, eyes closed, weight settled on one hip.",
    "wall-hands-clasped": "She leans back against the wall with hands clasped in front of her waist, ankles together, looking toward the camera.",
    "counter-turn-away": "She leans a hip on a counter and turns her head away over her shoulder, both hands resting lightly on the edge.",
    "car-window-lean": "She leans a forearm along a car's open window frame, weight on the near leg, the other hand relaxed, glancing sideways.",
    "doorway-hip-shift": "She leans in a doorway with her weight shifted to one hip, one hand on the frame at waist height, looking down slightly.",
    "wall-arm-overhead-relax": "She leans her back on the wall with one arm raised to rest a hand above her head, the other loose, gazing ahead calmly.",
    "railing-lean-look-up": "She leans her back against a railing, gripping it lightly, and tilts her head up to look above the camera.",
    "pillar-one-foot-forward": "She leans back against a pillar with one foot planted forward, arms relaxed at her sides, head level and eyes forward.",
    "counter-lean-side": "She rests her side and forearm along a counter, weight on that arm, the other hand on her hip, looking to the side.",
    "wall-crossed-arms-glance": "She leans her upper back on the wall with arms crossed and one ankle over the other, glancing toward the camera.",
    "car-roof-hand": "She leans her hip on a car and rests one hand on the roof, the other arm hanging, head turned slightly downward."
  },
  "Editorial & Fashion": {
    "angular-hip-thrust": "Standing with weight shoved onto one hip, both hands pressed flat against the crest of that hip, shoulders squared and chin lifted away from the camera.",
    "crossed-arm-lean": "Leaning back on an invisible line with arms tightly crossed over the chest, one elbow jutting sharply outward while she looks directly toward the camera.",
    "raised-arm-frame": "One arm lifted straight overhead to form a clean vertical line, the other resting on the waist, head tilted back to gaze upward.",
    "wide-stance-power": "Feet planted wide in a strong stance, hands loose at the sides, torso twisted slightly so one shoulder leads toward the lens.",
    "contrapposto-classic": "Weight on the back leg with the front knee softly bent, one hand at the collarbone, gaze cast over the shoulder.",
    "seated-knee-clasp": "Seated on the floor with one knee drawn up and both hands clasped around the shin, spine long and head turned in profile.",
    "diagonal-lunge": "Deep forward lunge with the trailing leg extended, both hands resting on the bent knee, eyes fixed on the horizon line.",
    "twisted-torso": "Hips facing forward while the upper body twists sharply to the side, one hand trailing across the opposite hip, looking back toward the camera.",
    "hands-behind-head": "Both hands laced behind the head with elbows fanned wide, chest open, chin dropped slightly and eyes toward the lens.",
    "profile-arch": "Standing in full profile with the back gently arched, one arm swept forward, gaze following the extended hand.",
    "crossed-ankle-stand": "Ankles crossed in a narrow elegant line, one hand grazing the neck, head tilted away with a downward glance.",
    "reaching-upward": "Both arms reaching up and slightly apart in a stretched line, weight on the toes, face turned upward.",
    "low-crouch-sculpt": "Low crouch balanced on the balls of the feet, forearms resting across the thighs, head lowered in a sculptural curl.",
    "asymmetric-arms": "One arm raised bent at the elbow overhead while the other drops straight down, torso tilted to exaggerate the diagonal, looking off-camera.",
    "shoulder-glance": "Back turned to the camera with head rotated over the shoulder, one hand resting lightly at the nape of the neck.",
    "knee-forward-angle": "Standing with one knee pushed forward and inward, creating a sharp bend, hands loosely on the thighs, gaze toward the camera.",
    "seated-side-lean": "Seated with legs angled to one side, weight braced on one straight arm, the other hand resting on the top knee, head lifted.",
    "arms-akimbo": "Hands firmly on both hips with elbows winged out, feet close together, chin raised and eyes level with the lens.",
    "floor-recline-prop": "Reclining on one hip propped up on a straight forearm, top leg bent, free hand resting on the thigh, looking calmly ahead.",
    "vertical-stretch": "Standing tall with both arms extended overhead and hands clasped, ribs lifted into a long vertical line, gaze straight forward.",
    "cross-body-reach": "One arm reaching across the body to the opposite shoulder, elbow forming a horizontal bar, head turned toward the reaching hand.",
    "back-arch-standing": "Feet together with the spine curved into a dramatic backward arch, one hand at the lower back, face tipped skyward.",
    "kneeling-tall-2": "Kneeling upright with thighs vertical, hands resting on the fronts of the thighs, shoulders drawn back and eyes toward the camera.",
    "side-step-diagonal": "Mid side-step with legs forming a wide triangle, one arm sweeping outward, torso leaning into the motion, gaze in the direction of travel.",
    "chin-hand-frame": "Standing straight with one hand cupped along the jawline and elbow supported by the other hand, head slightly cocked toward the lens.",
    "folded-forward": "Bent forward from the hips with a flat back, hands resting on the shins, head lifted so the face angles toward the camera.",
    "one-hand-hip-drop": "Weight dropped dramatically onto one hip with that hand on the waist, the other arm hanging loose, head tilted opposite the hip.",
    "seated-cross-legged": "Seated cross-legged with a tall spine, hands resting palm-down on the knees, chin level and gaze steady toward the camera.",
    "extended-leg-point": "Standing on one leg with the other extended forward and pointed, arms swept back for balance, looking down the extended line.",
    "shoulder-drop-lean": "One shoulder dropped low and the other lifted to create a strong tilt, arms relaxed, head following the lower shoulder.",
    "hands-clasped-front": "Standing with feet in a neat line and hands clasped low in front, spine elongated, head turned slightly to one side.",
    "dynamic-walk": "Captured mid-stride with one leg forward and arms swinging in opposition, torso leaning into the step, eyes ahead.",
    "seated-lean-back": "Seated leaning back on both extended arms, legs stretched forward and crossed at the ankles, face turned upward.",
    "elbow-out-frame": "One hand tucked into the waist with the elbow pushed far forward, the other arm straight down, gaze cast over the raised elbow.",
    "crouch-one-knee": "Down on one knee with the other foot planted, forearm braced on the raised knee, head lifted toward the camera.",
    "spiral-twist": "Standing with hips and shoulders counter-rotated into a spiral, both hands trailing to one side, looking back across the shoulder.",
    "arms-wrapped-waist": "Both arms wrapped softly around the waist in a self-embrace, shoulders curled inward, head bowed slightly to one side.",
    "heel-lift-poise": "Balanced on the ball of one foot with the heel lifted, opposite leg crossed behind, one hand skimming the hip, gaze forward.",
    "raised-chin-profile": "Full profile with chin lifted high, one arm folded across the midsection supporting the opposite elbow, hand near the chin.",
    "seated-knees-together": "Seated with knees pressed together and feet apart, hands resting on the knees, torso leaning forward and eyes to the lens.",
    "overhead-clasp-tilt": "Arms lifted overhead with wrists crossed, torso tilted to one side into a long curve, head following the lean.",
    "floor-reach-long": "Lying on one side with the top arm reaching over the head in a long line, lower arm folded under, gaze along the extended arm.",
    "wide-arm-span": "Standing with both arms extended straight out to the sides forming a horizontal line, feet together, head facing the camera.",
    "knee-in-twist": "Standing with one knee drawn up and hugged to the chest while balancing, torso twisted, looking over the shoulder.",
    "hip-jut-hand-down": "Hip jutted sharply to one side, both hands sliding down the front of the thighs, head dropped in a downward gaze.",
    "seated-chair-edge": "Perched on the edge of a seat with legs angled diagonally, hands resting between the knees, back straight and eyes forward.",
    "backbend-support": "Leaning into a supported backbend with both hands pressed behind on the hips, chest open wide, face tilted upward.",
    "crossed-arms-side": "Turned three-quarters away with arms crossed low, weight settled on the back leg, head rotated to meet the camera.",
    "reach-to-floor": "Bending sideways with one arm reaching toward the floor and the other lifted overhead, forming a long crescent, gaze downward.",
    "statuesque-stand": "Standing perfectly upright with feet together, arms straight at the sides and palms flat against the thighs, chin level and eyes ahead."
  },
  "Candid & Lifestyle": {
    "tucking-hair-behind-ear": "Standing with weight on one hip, she tilts her head slightly and lifts one hand to tuck a strand of hair behind her ear, looking off to the side.",
    "mid-laugh-hand-chest": "Caught mid-laugh, she leans back a little with one hand resting lightly on her chest and her chin lifted.",
    "walking-glance-back": "Mid-stride with one foot forward, she turns her upper body and glances back over her shoulder toward the camera.",
    "leaning-on-railing": "Resting both forearms on a railing, she leans forward slightly and looks out into the distance.",
    "hands-in-pockets": "Standing relaxed with both hands tucked into her pockets, weight shifted to one leg, gazing casually to the side.",
    "stretching-arms-up": "Reaching both arms overhead in a natural stretch, she arches slightly and closes her eyes.",
    "sipping-from-mug": "Holding a mug with both hands near her chin, she looks down into it as if about to take a sip.",
    "crouching-tying-shoe": "Crouched down on the balls of her feet, she reaches toward one shoe as though adjusting the lace, head bowed.",
    "seated-hugging-knees": "Sitting with her knees drawn up and arms wrapped around them, she rests her chin on her knees looking forward.",
    "checking-phone-down": "Standing with weight even, she holds a phone in both hands at waist height and looks down at the screen.",
    "waving-hello": "Raising one hand in a relaxed wave, she leans slightly forward with a friendly turn of her head toward the camera.",
    "arms-crossed-relaxed-3": "Standing with arms loosely crossed over her stomach, weight on one leg, glancing to the side.",
    "hand-on-neck": "Resting one hand at the back of her neck with the elbow raised, she looks down and slightly away.",
    "sitting-legs-crossed": "Seated on the floor with legs crossed, hands resting on her ankles, she looks up and to the side.",
    "leaning-against-wall": "Leaning one shoulder against a wall with ankles casually crossed, she looks toward the camera.",
    "looking-over-shoulder": "With her back partly turned, she glances back over one shoulder with a relaxed tilt of her head.",
    "pushing-hair-back": "Running both hands up through her hair from the temples, she tilts her head back with eyes half closed.",
    "seated-elbow-on-table": "Sitting at a table, she props one elbow on the surface and rests her cheek against her hand, gazing forward.",
    "hands-clasped-front-2": "Standing with both hands loosely clasped in front of her, she tilts her head slightly and looks to the side.",
    "mid-step-turning": "Turning mid-step with one hand lightly swinging, she looks toward something behind her.",
    "adjusting-sleeve": "Looking down at one wrist, she uses the other hand to fold or adjust a sleeve.",
    "seated-leaning-back": "Reclining back on both hands placed behind her while seated, she lifts her chin and looks upward.",
    "holding-book-reading": "Holding an open book in both hands at chest level, she tilts her head down as if reading.",
    "resting-chin-hand": "Sitting with one elbow on a surface, she rests her chin on her fist and looks off thoughtfully to one side.",
    "hands-on-hips": "Standing with both hands on her hips and weight shifted, she looks slightly downward and to the side.",
    "reaching-up-shelf": "Reaching one arm up as if toward a high shelf, she rises slightly onto her toes with head tilted upward.",
    "kneeling-one-knee": "Kneeling on one knee with the other foot planted, she rests a forearm on her raised knee and looks ahead.",
    "blowing-hair-off-face": "Puffing out her cheeks to blow a strand of hair off her face, she tilts her chin up with a playful expression.",
    "carrying-tote-bag": "Standing with a tote bag slung over one shoulder held by one hand, she turns her head to glance sideways.",
    "laughing-covering-mouth": "Caught laughing, she brings one hand up to cover her mouth while her shoulders rise slightly.",
    "twirling-strand-hair": "Twisting a strand of hair around one finger, she looks down and slightly away with a soft tilt of her head.",
    "sitting-on-steps": "Seated on a step with elbows resting on her thighs and hands loosely clasped, she looks forward.",
    "stretching-neck-side": "Tilting her head to one side to stretch her neck, she lets both arms hang loose and closes her eyes briefly.",
    "hand-shielding-eyes": "Raising one hand to her brow as if shielding her eyes, she gazes into the distance.",
    "leaning-forward-listening": "Leaning forward slightly with hands resting on her thighs, she turns her ear toward the camera as if listening.",
    "arms-behind-back": "Standing with both hands clasped behind her back and shoulders relaxed, she looks straight toward the camera.",
    "crouched-petting-motion": "Crouched low with one hand extended forward at knee level, she looks down gently as if greeting a pet.",
    "holding-coffee-walking": "Walking casually while holding a takeaway cup in one hand, she glances to the side mid-step.",
    "seated-crossed-ankle": "Sitting on a chair with one ankle crossed over the opposite knee, she leans back and looks to the side.",
    "rubbing-eyes-tired": "Bringing one hand up to gently rub one eye, she tilts her head down in a relaxed, sleepy gesture.",
    "hands-warming-mug": "Cupping a warm mug in both hands close to her body, she looks down with a soft, calm posture.",
    "pointing-into-distance": "Extending one arm to point off into the distance, she follows the direction with her gaze.",
    "seated-sideways-chair": "Sitting sideways on a chair with one arm draped over its back, she turns her head toward the camera.",
    "fixing-collar": "Reaching both hands up to adjust her collar, she looks down slightly with her chin tucked.",
    "standing-relaxed-swaying": "Standing with weight loosely shifted and arms hanging naturally, she glances upward and to the side.",
    "leaning-chin-on-fence": "Resting both hands and her chin lightly on the top of a fence, she gazes out ahead.",
    "scratching-head-thinking": "Scratching the top of her head with one hand, she looks upward as if puzzled or thinking.",
    "holding-flowers": "Cradling a small bunch of flowers in the crook of one arm, she lowers her head to look at them.",
    "seated-writing-notebook": "Seated with a notebook on her lap, she leans over it holding a pen and looks down at the page.",
    "stretching-back-twist": "Placing one hand at her lower back, she twists gently at the waist and looks over the same shoulder."
  },
  "Selfie (Handheld)": {
    "selfie-classic-arm-out": "She holds her phone in one outstretched hand just above eye level and looks directly into it, the near arm and shoulder angled toward the lens in a classic handheld selfie.",
    "selfie-high-angle": "She lifts the phone high above her face and tips her chin up toward it, the raised arm creating a steep downward angle as she gazes into the lens.",
    "selfie-two-hands": "She cradles the phone in both hands close to her face, elbows drawn in, looking softly into the lens with her head tilted slightly to one side.",
    "selfie-side-glance": "She holds the phone off to one side at arm's length and glances toward it sideways, cheek turned and chin dipped in a candid handheld selfie.",
    "selfie-peace-sign": "She extends the phone in one hand while the other lifts a two-finger peace sign near her cheek, smiling into the lens with a playful head tilt.",
    "selfie-low-angle": "She holds the phone low near her chest and tilts her face down toward it, the upward gaze foreshortened in a low-angle handheld selfie.",
    "selfie-blowing-kiss": "She stretches the phone out in one hand and puckers toward the lens as if blowing a kiss, the free hand raised lightly beside her mouth.",
    "selfie-hair-toss": "She holds the phone at arm's length with one hand while the other sweeps through her hair, head tipping back as she looks into the lens.",
    "selfie-over-shoulder": "She turns her back partly to the phone held out to one side and glances back over her shoulder into the lens, chin near her raised arm.",
    "selfie-lying-overhead": "Lying on her back, she holds the phone directly overhead in both hands and gazes straight up into the lens, hair fanned around her face.",
    "selfie-outstretched-laugh": "She flings the phone out to arm's length and laughs toward the lens, shoulders rising and the free hand drifting up near her collarbone.",
    "selfie-cheek-to-lens": "She brings the phone in close and turns one cheek toward it, eyes cutting sideways to the lens in an intimate close-cropped handheld selfie.",
    "selfie-both-arms-up": "She raises the phone overhead with both hands and arches slightly back, face tilted up into the lens in a stretched, celebratory selfie.",
    "selfie-walking-vlog": "She holds the phone out ahead of her at eye level as if filming while mid-step, talking toward the lens with her free arm swinging naturally.",
    "selfie-chin-in-hand": "She holds the phone at arm's length with one hand while the other cups her chin, head tilted thoughtfully toward the lens.",
    "selfie-wink": "She extends the phone in one hand and throws a light wink toward the lens, the free hand resting near her jaw with a playful smile.",
    "selfie-pout": "She holds the phone slightly above and out, pushing her lips into a soft pout, eyes half-lidded and directed into the lens.",
    "selfie-seated-relaxed": "Seated and leaning back comfortably, she holds the phone out at chest height and looks up into the lens with a relaxed smile.",
    "selfie-sun-squint": "Outdoors in bright light, she holds the phone out with one hand and lightly squints into the lens, the other hand shading her brow.",
    "selfie-hand-on-cheek": "She reaches the phone out to one side while pressing the other palm softly to her cheek, head tilted into it, gazing into the lens.",
    "selfie-lying-front": "Lying on her stomach and propped on her forearms, she holds the phone on the surface just ahead and looks up into the lens.",
    "selfie-looking-away": "She holds the phone out at eye level but lets her gaze drift off past it, chin lifted in a candid, unposed handheld selfie.",
    "selfie-coffee-cup": "She holds a takeaway cup near her chin in one hand and the phone out in the other, glancing into the lens over the rim.",
    "selfie-face-frame": "She brings both hands up beside her face, phone tucked in one, loosely framing her cheeks as she smiles into the lens.",
    "selfie-shoulder-shrug": "She holds the phone out to one side and lifts both shoulders in a light shrug, head tilted toward one shoulder with a soft grin at the lens."
  },
  "Selfie (Mirror)": {
    "mirror-selfie-full-length": "She stands before a full-length mirror holding her phone at chest height toward the glass, weight on one hip and the free hand relaxed, looking at her reflection.",
    "mirror-selfie-phone-face": "She faces a mirror with the phone raised to partly cover her face, the screen aimed at the glass, her visible eye meeting her reflection.",
    "mirror-selfie-hip-pop": "She poses in a mirror with one hip popped and the phone held low against her waist pointed at the glass, the other hand resting on her hip.",
    "mirror-selfie-side-profile": "She turns her side to a mirror and extends the phone toward the glass, glancing back at her reflection over her shoulder in a profile mirror shot.",
    "mirror-selfie-bathroom": "She stands square to a bathroom mirror holding the phone up beside her head toward the glass, the other arm hanging loose, gaze on her reflection.",
    "mirror-selfie-elevator": "She leans a shoulder against an elevator or lift wall facing a mirrored panel, phone raised toward the glass, looking at her reflection with a slight tilt.",
    "mirror-selfie-seated": "Seated on the floor before a mirror, she holds the phone up toward the glass with one hand and rests the other on a bent knee, watching her reflection.",
    "mirror-selfie-back-turned": "She stands with her back to a mirror and twists her upper body to aim the phone over her shoulder at the glass, glancing back at her reflection.",
    "mirror-selfie-two-hand-frame": "She grips the phone in both hands at chest level pointed at a mirror, elbows out, leaning slightly toward the glass with a steady gaze at her reflection.",
    "mirror-selfie-leaning-in": "She leans in close to a mirror with one hand flat on the frame and the phone held low toward the glass, chin lifted as she studies her reflection.",
    "mirror-selfie-hand-on-hip": "She stands facing a mirror with one hand planted on her hip and the phone raised beside her face toward the glass, weight shifted onto one leg.",
    "mirror-selfie-three-quarter": "She angles her body three-quarters to a mirror and points the phone at the glass, glancing at her reflection with her near shoulder leading.",
    "mirror-selfie-crouch": "She crouches low in front of a mirror with the phone held out toward the glass at eye level, forearm resting on a bent knee, watching her reflection.",
    "mirror-selfie-overhead": "She raises the phone high toward a mirror and tips her chin up, the reflection catching a steep high-angle view of her face and the raised arm.",
    "mirror-selfie-wardrobe": "She stands before a tall wardrobe mirror checking her outfit, phone held at her waist toward the glass, the free hand smoothing the fabric at her hip.",
    "mirror-selfie-car-window": "She catches her reflection in a tinted car window and lifts the phone toward it, head tilted, the free hand tucking hair behind her ear.",
    "mirror-selfie-gym": "She stands square to a gym mirror with the phone raised beside her head toward the glass, the other hand resting on her hip in an athletic stance.",
    "mirror-selfie-looking-down": "She stands before a mirror looking down at the phone screen held at her waist toward the glass, chin tucked, reflection caught in a quiet downward gaze.",
    "mirror-selfie-hair-touch": "She faces a mirror with one hand lifted to her hair and the phone held out toward the glass in the other, glancing at her reflection through her fingers.",
    "mirror-selfie-peace-sign": "She flashes a two-finger peace sign toward a mirror while holding the phone beside her face at the glass, reflection meeting her playful gaze.",
    "mirror-selfie-legs-crossed": "She stands before a full-length mirror with ankles crossed and weight loose, phone held at her hip toward the glass, head tilted at her reflection.",
    "mirror-selfie-lean-wall": "She leans her back against a mirrored wall and turns her head to aim the phone at the glass beside her, reflection caught in a relaxed sideways glance.",
    "mirror-selfie-outfit-check": "She turns slightly and glances down at her outfit in a mirror, phone held low toward the glass, the free hand adjusting the hem at her waist.",
    "mirror-selfie-close-face": "She stands close to a mirror with the phone raised near her cheek toward the glass, filling the reflection with a tight, intimate view of her face.",
    "mirror-selfie-head-tilt": "She faces a mirror square-on with the phone held at chest height toward the glass and tilts her head gently to one side, gaze soft on her reflection."
  },
  "Exotic": {
    "arched-spine-standing": "Standing tall with her spine arched deeply backward, chest lifted and both arms reaching overhead, chin following the curve.",
    "serpentine-torso": "Hips pushed to one side and ribs counter-shifted to the other, her torso drawn into a long S-curve, one hand tracing the waist.",
    "floor-arch-back": "Lying on her back with hips lifted clear of the floor, weight on her shoulders and feet, one knee dropped open.",
    "cobra-lift": "Face down on the floor, propped high on straight arms with her spine arched and head tipped back.",
    "kneeling-back-bend": "Kneeling upright with her back arched and both hands reaching behind to her heels, throat exposed to the light.",
    "leg-extended-vertical": "Lying on her side with the top leg extended straight up toward the ceiling, one hand steadying the ankle.",
    "silk-drag": "Standing in profile drawing a length of fabric slowly across her body, the cloth trailing behind her in the air.",
    "fabric-overhead": "Both arms lifted overhead holding a sheer panel of fabric that falls open around her like a canopy.",
    "wind-caught-silhouette": "Standing side-on against the light with fabric lifting away from her body, her outline sharp inside it.",
    "hip-thrown-hard": "Weight dropped hard onto one hip with the opposite leg extended long and pointed, one arm sweeping overhead.",
    "sculptural-crouch": "Crouched low with knees wide and both hands planted between them, spine long and head lifted toward the lens.",
    "shoulder-stand-drape": "On her upper back with legs folded overhead, fabric spilling down toward her shoulders.",
    "table-top-recline": "Reclining backward across a low surface with her head hanging past the edge and hair falling free.",
    "hands-frame-face": "Both hands raised to frame her face from either side, elbows wide and symmetrical, gaze straight down the lens.",
    "twisted-seated-reach": "Seated with legs folded to one side, torso twisted hard the other way, one arm reaching across the floor.",
    "leg-hooked-high": "Standing beside a wall with one leg lifted and hooked against it, hips square to the camera.",
    "prone-legs-crossed-up": "Lying face down on her forearms with both lower legs raised and crossed at the ankles above her.",
    "kneel-lean-far-back": "Kneeling with her weight carried far back onto both hands behind her, hips lifted and chin raised.",
    "diagonal-floor-stretch": "Stretched diagonally across the frame on her side, body drawn into one long unbroken line from fingertips to toes.",
    "elbow-prop-arch": "On her side propped on one elbow with the waist dipped low and hips stacked high above it.",
    "overhead-clasp-lean": "Standing with both hands clasped high overhead and the whole body leaning into a long side bend.",
    "spiral-standing-turn": "Mid-turn with hips facing away and shoulders wound back toward the camera, one arm trailing.",
    "seated-legs-scissor": "Seated on the floor with legs scissored open in a wide V, leaning back on both straight arms.",
    "mirror-floor-arch": "Lying on her back beside a mirror with her spine arched, the reflection doubling the curve.",
    "hair-sweep-back-bend": "Bending backward from the waist with one hand sweeping her hair away from her face.",
    "one-knee-up-arch": "Seated with one knee drawn high and the spine arched away from it, head tipped back.",
    "stretch-cat-pose": "On hands and knees with her chest dropped low toward the floor and hips high, chin lifted forward.",
    "standing-side-extension": "Standing on one leg with the other extended straight out to the side, both arms opened wide for balance.",
    "wall-press-arch": "Back pressed flat to a wall with hips pushed forward and shoulders rolled back, one knee bent.",
    "reclined-throat-line": "Reclining on her elbows with her head dropped fully back, the line of her throat facing the light.",
    "floor-spiral-legs": "On her back with both legs spiralled over to one side and shoulders held flat to the floor.",
    "high-kneel-reach-up": "Up on both knees with one arm stretched straight overhead and the other trailing at her thigh.",
    "veil-across-face": "Standing still with a translucent fabric drawn across the lower half of her face, eyes above it toward the lens.",
    "arm-wrap-turn": "Turning away with one arm wrapped across her own waist and the opposite shoulder dipped low.",
    "supine-legs-vertical": "Flat on her back with both legs raised straight and pressed together, arms flat at her sides.",
    "hip-lift-bridge": "In a low bridge with hips pushed high, feet flat and both arms extended overhead on the floor.",
    "seated-back-arch-hands": "Seated with hands planted behind, chest driven forward and up, head fallen back between her shoulders.",
    "standing-fold-forward": "Folded forward from the hips with hands near the floor, head turned to find the camera sideways.",
    "leg-cross-standing-twist": "Standing with ankles crossed and the torso twisted hard toward the lens, hands loose at her sides.",
    "recline-fabric-pool": "Reclining on one hip with fabric pooled around her, one arm draped along the length of her body.",
    "shoulder-roll-back": "Standing with both shoulders rolled far back and down, chest open, arms hanging long behind the line of her body.",
    "kneel-side-stretch": "Kneeling with one leg extended straight to the side and the torso arced over it, one arm reaching along the leg.",
    "floor-elbow-arch-high": "Propped on both elbows with hips lifted high off the floor and the head dropped back.",
    "spiral-hair-lift": "Both hands buried in her hair lifting it clear of her neck, elbows high, torso twisted to one side.",
    "long-lunge-reach": "Sunk into a long low lunge with the back leg extended flat and both arms reaching forward past her knee.",
    "sit-lean-far-side": "Seated with legs folded and the whole torso leaned far over one hip onto a single supporting hand.",
    "prone-arch-look-back": "Lying on her front, chest raised on straight arms, head turned to look back over her own shoulder.",
    "standing-knee-cross": "Standing with one knee crossed tightly over the other and hips angled, one hand resting at the outer thigh.",
    "reach-to-ceiling-rise": "Rising onto the balls of both feet with both arms stretched their full length toward the ceiling.",
    "floor-frame-legs": "On her back with knees bent and feet flat, arms folded above her head to frame the shot."
  },
  "Lustful": {
    "over-shoulder-smoulder": "Turned away from the camera with her head rotated back over one bare shoulder, eyes locked on the lens.",
    "lip-touch-glance": "Fingertips resting lightly at her lower lip, chin dipped, eyes lifted to the camera.",
    "strap-off-shoulder": "One hand easing a shoulder strap down her upper arm, head tilted the opposite way, gaze steady.",
    "hair-grasp-back": "One hand gathering her hair at the nape and pulling it back, chin lifted and throat exposed.",
    "reclined-invite": "Lying back on both elbows with knees drawn up and slightly apart, holding the camera's eye.",
    "hand-on-inner-thigh": "Seated with one hand resting high on her own thigh, knees angled toward the lens, gaze level.",
    "eyes-closed-head-back": "Head dropped back with eyes closed and lips just parted, shoulders loose.",
    "kneel-hands-slide-thighs": "Kneeling upright with both hands sliding slowly down the tops of her thighs, eyes on the camera.",
    "collarbone-trace": "One hand tracing along her own collarbone toward the shoulder, head turned slightly away.",
    "bite-lip-side-glance": "Lower lip caught between her teeth, face angled away with eyes cut back toward the lens.",
    "sheet-clutch": "Lying on her side clutching a sheet loosely to her chest, one leg drawn up, looking straight at the camera.",
    "back-to-camera-look": "Standing with her back fully to the camera and her head turned to find the lens over one shoulder.",
    "prone-ankles-crossed": "Lying on her front with ankles crossed in the air behind her, chin propped on both hands, smiling at the lens.",
    "reach-toward-lens": "Lying back with one arm extended slowly toward the camera, fingers relaxed, eyes half-lowered.",
    "hip-tilt-hand-waist": "Standing with one hip pushed out and a hand resting low on her own waist, weight on the opposite leg.",
    "seated-knees-apart-lean": "Seated on the edge of a chair leaning forward, forearms on her knees, gaze up into the lens.",
    "hair-over-one-eye": "Hair fallen forward across one side of her face, chin dipped, the visible eye fixed on the camera.",
    "shoulder-kiss-own": "Head turned down toward her own shoulder with lips almost touching it, eyes raised to the lens.",
    "lying-side-hand-hip": "On her side with one hand resting along the curve of her hip, top leg bent forward, direct gaze.",
    "arch-on-bed": "On her back across a bed with her spine arched and both arms stretched above her head.",
    "robe-slipping": "Standing with a robe fallen open and held loosely closed at the waist by one hand, looking over her shoulder.",
    "chin-lift-eyes-down": "Chin raised high with her eyes lowered toward the camera beneath it, mouth relaxed.",
    "seated-legs-crossed-lean-in": "Seated with legs crossed high at the thigh, leaning in toward the camera with both hands on the front knee.",
    "hands-behind-head-recline": "Reclining with both hands laced behind her head and elbows wide, body long and open.",
    "wall-lean-hip-out": "Leaning one shoulder against a wall with the near hip pushed out toward the camera, head tipped back against it.",
    "kneel-sit-back-arch": "Kneeling and sitting back on her heels with her chest lifted and both hands resting behind her.",
    "finger-hook-strap": "One finger hooked under a strap at her shoulder, held still, eyes steady on the lens.",
    "lying-back-head-tilt": "Flat on her back with her head tilted back toward the camera and hair spilling out around it.",
    "slow-turn-glance": "Caught mid-turn away from the lens with her eyes still holding it and one hand at her waist.",
    "seated-floor-lean-back": "Seated on the floor leaning back onto both hands with legs extended and ankles crossed, chin raised.",
    "hand-through-hair-up": "Both hands pushing up through her hair from the temples, elbows raised, gaze straight ahead.",
    "prone-look-up": "Lying on her front propped on both forearms, shoulders drawn in, looking up into the camera.",
    "thigh-cross-seated": "Seated with one thigh crossed tightly over the other and the top foot pointed, hands resting behind her.",
    "shoulder-forward-lean": "Leaning toward the lens with one shoulder rolled forward and the opposite arm crossing low.",
    "neck-exposed-side": "Head turned fully to one side with the neck long and exposed, eyes closed, shoulders dropped.",
    "sit-legs-tucked-glance": "Sitting with both legs tucked to one side and a hand on the floor, glancing back over her shoulder.",
    "stretch-waking": "Mid-stretch with both arms overhead and her back arched, eyes half open toward the camera.",
    "hands-on-headboard": "Kneeling upright with both hands raised to grip a headboard above her, chin lowered, eyes up.",
    "leg-drawn-up-side": "On her side with the top leg drawn up high toward her chest and one hand holding the shin.",
    "smoulder-direct": "Square to the camera, shoulders relaxed and chin slightly down, holding a long unbroken look into the lens.",
    "back-arch-seated-edge": "Perched on the edge of a surface with her spine arched and both hands gripping the edge beside her hips.",
    "fingers-at-jaw": "Fingertips resting under her jaw and tilting her own face toward the light, gaze angled to the lens.",
    "lying-legs-bent-up": "On her back with both knees bent and feet flat, one hand resting on her stomach, head turned to the camera.",
    "hip-swivel-back-view": "Standing with hips swivelled away and shoulders squared back toward the camera, one hand at the small of her back.",
    "kneel-forward-hands-floor": "On her knees leaning forward onto both hands, shoulders low, eyes lifted straight into the lens.",
    "shoulder-glance-hair-down": "Hair falling loose down her back, head turned so one eye finds the camera past her shoulder.",
    "seated-lean-knees-together": "Seated with knees pressed together and toes turned in, leaning forward with hands between them.",
    "recline-one-arm-overhead": "Reclining with one arm thrown above her head and the other resting along her waist, gaze on the lens.",
    "chin-on-shoulder-back": "Back to the camera with her chin dropped onto her own shoulder, eyes cut sideways to the lens.",
    "slow-sink-crouch": "Sinking into a slow crouch with knees together and both hands sliding down her thighs, eyes forward."
  }
}
