import * as React from "react";
import { cva } from "class-variance-authority";
import { X } from "lucide-react";
import { cn } from "@/lib/utils";

// Toasts. Generated by the shadcn CLI for Radix and then shipped WITHOUT Radix,
// which left two problems that only show up the first time one fires:
//
//   * ToastProvider and ToastViewport were byte-identical fixed containers, and
//     Toaster nested one inside the other — two stacked overlays, the inner one
//     always empty.
//   * the base class carried a wall of data-[swipe=…] / data-[state=…] selectors
//     that only Radix ever sets. Dead weight, and they made the real styling hard
//     to find.
//
// Provider is now a passthrough and Viewport is the single container. Styling
// matches the surfaces the rest of the app actually uses (#0d0d0f panels, white
// hairline rings) rather than the token defaults.

const ToastProvider = ({ children }) => <>{children}</>;

const ToastViewport = React.forwardRef(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      "pointer-events-none fixed inset-x-0 bottom-0 z-[100] flex flex-col items-end gap-2 p-4",
      "sm:left-auto sm:right-0 sm:max-w-[420px]",
      className,
    )}
    {...props}
  />
));
ToastViewport.displayName = "ToastViewport";

const toastVariants = cva(
  "group pointer-events-auto relative flex w-full items-start gap-3 overflow-hidden " +
    "rounded-xl px-3.5 py-3 pr-9 shadow-xl ring-1 backdrop-blur " +
    "animate-in slide-in-from-bottom-2 fade-in duration-200",
  {
    variants: {
      variant: {
        default: "bg-[#141417]/95 text-zinc-100 ring-line",
        destructive: "bg-rose-950/90 text-rose-100 ring-rose-500/30",
      },
    },
    defaultVariants: { variant: "default" },
  },
);

const Toast = React.forwardRef(({ className, variant, ...props }, ref) => (
  <div ref={ref} className={cn(toastVariants({ variant }), className)} {...props} />
));
Toast.displayName = "Toast";

const ToastTitle = React.forwardRef(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("text-[12px] font-medium leading-snug", className)}
    {...props} />
));
ToastTitle.displayName = "ToastTitle";

const ToastDescription = React.forwardRef(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("text-[11px] leading-snug opacity-70 break-words", className)}
    {...props}
  />
));
ToastDescription.displayName = "ToastDescription";

const ToastClose = React.forwardRef(({ className, ...props }, ref) => (
  <button
    ref={ref}
    aria-label="Dismiss"
    className={cn(
      "absolute right-2 top-2 rounded-md p-1 opacity-40 transition-opacity hover:opacity-100",
      className,
    )}
    {...props}
  >
    <X className="h-3.5 w-3.5" />
  </button>
));
ToastClose.displayName = "ToastClose";

export {
  Toast,
  ToastClose,
  ToastDescription,
  ToastProvider,
  ToastTitle,
  ToastViewport,
};
